# This is the default format.
# For more see: http://jekyllrb.com/docs/permalinks/
# default: /:categories/:year/:month/:day/:title
permalink: /post/:title/
date_format: "%F"

title:       "reznoa의 동굴폐인 놀이터"
description: 만화, 영화, 음악, 게임 등 재밌는 거라면 뭐든지.
author:
 name:    reznoa
 email:   reznoa+blog@gmail.com
 github:  reznoa
 twitter: reznoa

url: "http://reznoa.github.io"

favicon: /images/favicon.ico

# Build settings
markdown: kramdown
highlighter: rouge

kramdown:
 input: GFM

feed:
 type:     part # full | part
 truncate: 150  # ignored if type is full

disqus_shortname: 'rezlog'
google_analytics: 'UA-2606866-2'
google_search:    '001425118784033334076:fhu_ptlyqxa'
google_adsense:
 client: 'ca-pub-1236059159470666'
 slot:   4647313530
paypal_button:
 data: "-----BEGIN PKCS7-----MIIHFgYJKoZIhvcNAQcEoIIHBzCCBwMCAQExggEwMIIBLAIBADCBlDCBjjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRYwFAYDVQQHEw1Nb3VudGFpbiBWaWV3MRQwEgYDVQQKEwtQYXlQYWwgSW5jLjETMBEGA1UECxQKbGl2ZV9jZXJ0czERMA8GA1UEAxQIbGl2ZV9hcGkxHDAaBgkqhkiG9w0BCQEWDXJlQHBheXBhbC5jb20CAQAwDQYJKoZIhvcNAQEBBQAEgYBWLvsE3pszi29CKD+bpJP0TYkrj7+SzO1q9zfpmFoT2Hqm1uRbocPOF+MXCpCkOlSvkcMRUQU8xIxeWDzKSxnBu1nCNXBZvH0a8pzgK+EOxGCrwj7NB5aNXHGNkk2X1ZSnHL8WGIwnKOVO4i2q+yWz/HVSZnFYBbxWtKdaJQeGkjELMAkGBSsOAwIaBQAwgZMGCSqGSIb3DQEHATAUBggqhkiG9w0DBwQIpkt4+tm/Zg2AcN4BFKz5gAmSyOuMiKInfJhx0BS9GG5Hi5Y71Xg481Y4QbUdM2GN0tJvPVWk6DpPjRr+NzF2GmUhn8ghi54lo6O7jdBBi40QZyUMV5c9ZMu3Vr0t4TSYLp5FNRbQsCOFTDpIMdtayhIRfBgufZsGHBmgggOHMIIDgzCCAuygAwIBAgIBADANBgkqhkiG9w0BAQUFADCBjjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRYwFAYDVQQHEw1Nb3VudGFpbiBWaWV3MRQwEgYDVQQKEwtQYXlQYWwgSW5jLjETMBEGA1UECxQKbGl2ZV9jZXJ0czERMA8GA1UEAxQIbGl2ZV9hcGkxHDAaBgkqhkiG9w0BCQEWDXJlQHBheXBhbC5jb20wHhcNMDQwMjEzMTAxMzE1WhcNMzUwMjEzMTAxMzE1WjCBjjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRYwFAYDVQQHEw1Nb3VudGFpbiBWaWV3MRQwEgYDVQQKEwtQYXlQYWwgSW5jLjETMBEGA1UECxQKbGl2ZV9jZXJ0czERMA8GA1UEAxQIbGl2ZV9hcGkxHDAaBgkqhkiG9w0BCQEWDXJlQHBheXBhbC5jb20wgZ8wDQYJKoZIhvcNAQEBBQADgY0AMIGJAoGBAMFHTt38RMxLXJyO2SmS+Ndl72T7oKJ4u4uw+6awntALWh03PewmIJuzbALScsTS4sZoS1fKciBGoh11gIfHzylvkdNe/hJl66/RGqrj5rFb08sAABNTzDTiqqNpJeBsYs/c2aiGozptX2RlnBktH+SUNpAajW724Nv2Wvhif6sFAgMBAAGjge4wgeswHQYDVR0OBBYEFJaffLvGbxe9WT9S1wob7BDWZJRrMIG7BgNVHSMEgbMwgbCAFJaffLvGbxe9WT9S1wob7BDWZJRroYGUpIGRMIGOMQswCQYDVQQGEwJVUzELMAkGA1UECBMCQ0ExFjAUBgNVBAcTDU1vdW50YWluIFZpZXcxFDASBgNVBAoTC1BheVBhbCBJbmMuMRMwEQYDVQQLFApsaXZlX2NlcnRzMREwDwYDVQQDFAhsaXZlX2FwaTEcMBoGCSqGSIb3DQEJARYNcmVAcGF5cGFsLmNvbYIBADAMBgNVHRMEBTADAQH/MA0GCSqGSIb3DQEBBQUAA4GBAIFfOlaagFrl71+jq6OKidbWFSE+Q4FqROvdgIONth+8kSK//Y/4ihuE4Ymvzn5ceE3S/iBSQQMjyvb+s2TWbQYDwcp129OPIbD9epdr4tJOUNiSojw7BHwYRiPh58S1xGlFgHFXwrEBb3dgNbMUa+u4qectsMAXpVHnD9wIyfmHMYIBmjCCAZYCAQEwgZQwgY4xCzAJBgNVBAYTAlVTMQswCQYDVQQIEwJDQTEWMBQGA1UEBxMNTW91bnRhaW4gVmlldzEUMBIGA1UEChMLUGF5UGFsIEluYy4xEzARBgNVBAsUCmxpdmVfY2VydHMxETAPBgNVBAMUCGxpdmVfYXBpMRwwGgYJKoZIhvcNAQkBFg1yZUBwYXlwYWwuY29tAgEAMAkGBSsOAwIaBQCgXTAYBgkqhkiG9w0BCQMxCwYJKoZIhvcNAQcBMBwGCSqGSIb3DQEJBTEPFw0xODA3MDIwNTIxNTBaMCMGCSqGSIb3DQEJBDEWBBRZI+4aNLtDilD7z+5JZLaJffSMdDANBgkqhkiG9w0BAQEFAASBgDLr5JuhLJsSiFq4TMEEVHlofft+D6EBwtiRQtiSDSneCzJb1+oW1pdYZ7kVs5AMID+Xl88sgkkgLzW3zZC+OAlQ7oVOLySKilm8hHr4+anzFtER9Hjl2Ul9rwJhbEcjn2FG7zdwR1+jYQhwnkiYb4ESP6d8q3r1yK+BqEPud7oO-----END PKCS7-----"
 type: "donate_SM" # donate_SM | donate_LG | donateCC_LG
toss:
 id: 'reznoa'

# Navigation
links:
 - title:     Home
   url:       /
   fa_icon:   fa-home
   icon_only: true
#- title:     About
#  url:       /about/
#  fa_icon:   fa-user
#  icon_only: true
 - title:     Archive
   url:       /archive/
   fa_icon:   fa-calendar
   icon_only: true
 - title:     Categories
   url:       /categories/
   fa_icon:   fa-sitemap
   icon_only: true
 - title:     Tags
   url:       /tags/
   fa_icon:   fa-tags
   icon_only: true
 - title:     Guestbook
   url:       /guestbook/
   fa_icon:   fa-comments
   icon_only: true
 - title:     Search
   id:        site-search-btn
   url:       /search/
   fa_icon:   fa-search
   icon_only: true
 - title:     Feed
   url:       /feed.xml
   fa_icon:   fa-feed
   icon_only: true

paginate:      10
paginate_path: "page:num"

gems:
 - jemoji
 - jekyll-sitemap
 - jekyll-paginate

exclude:
 - _posts/2018-05-16-family-book-1-grandmother-book-review.md
 - _posts/2018-05-16-family-book-2-grandfather-book-review.md
 - _posts/2018-05-16-family-book-3-mother-book-review.md
 - _posts/2018-05-16-family-book-4-father-book-review.md
