# This is the default format.
# For more see: http://jekyllrb.com/docs/permalinks/
# default: /:categories/:year/:month/:day/:title
permalink: /post/:title/
date_format: "%F"

title:       "reznoa의 동굴폐인 놀이터"
description: 만화, 영화, 음악, 게임 등 재밌는 거라면 뭐든지.
author:
 name:    reznoa
 email:   reznoa+blog@gmail.com
 github:  reznoa
 twitter: reznoa

url: "http://reznoa.wo.tc"

favicon: /images/favicon.ico

# Build settings
markdown: kramdown
highlighter: rouge

kramdown:
 input: GFM

feed:
 type:     part # full | part
 truncate: 150  # ignored if type is full

disqus_shortname: 'rezlog'
google_analytics: 'UA-2606866-2'
google_search:    '001425118784033334076:fhu_ptlyqxa'

# Navigation
links:
 - title:     Home
   url:       /
   fa_icon:   fa-home
   icon_only: true
#- title:     About
#  url:       /about/
#  fa_icon:   fa-user
#  icon_only: true
 - title:     Archive
   url:       /archive/
   fa_icon:   fa-calendar
   icon_only: true
#- title:     Categories
#  url:       /categories/
#  fa_icon:   fa-tags
#  icon_only: true
 - title:     Tags
   url:       /tags/
   fa_icon:   fa-tags
   icon_only: true
 - title:     Guestbook
   url:       /guestbook/
   fa_icon:   fa-comments
   icon_only: true
 - title:     Search
   id:        site-search-btn
   url:       /search/
   fa_icon:   fa-search
   icon_only: true
 - title:     Feed
   url:       /feed.xml
   fa_icon:   fa-feed
   icon_only: true

paginate:      10
paginate_path: "page:num"

gems:
 - jemoji
 - jekyll-mentions
 - jekyll-sitemap
 - jekyll-paginate

jekyll-mentions:
 base_url: https://twitter.com
